### ISSUE TITLE
Create a GitHub Actions Workflow

### ISSUE THREAD

**Issue by JorgeSquared** [webgptorg/webgpt-docs#1]
To add ease to the workflow and enable best practices, we should set up continuous deployment:
```yaml
name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'  # This ensures deployment only occurs for pushes to main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
